package chamCore;

/*
 * QueryFilmList is the list structure generated by querying the Core list or another list of FilmNodes
 * it builds itself from another list, but returning results with specified parameters
 */
public class QueryFilmList extends AbstractFilmList {

	/*
	 * Empty constructor
	 */
	public QueryFilmList() {
		super();	//TODO double check this
	}

	/*
	 * Builds a QueryFilmList by copying all nodes of the core list that contain the provided parameter
	 * This is the typical use case for Query List builds; a return for search function
	 */
	public QueryFilmList(CoreFilmList core, String searchParameter) {
		int len = core.list.size();
		for(int i=0; i<len; i++) {
			if(core.list.get(i).contains(searchParameter)) {
				list.add(new FilmNode(core.list.get(i)));	//creates copy of node TODO check if its better to set reference
			}
		}
	}
}
